### ISSUE TITLE
No stable versions available?

### ISSUE THREAD

**Issue by peterboorsma** [GawainLynch/bolt-extension-lazyload#1]
Seems there's no right version for Bolt 3.0.9. Is this right?
![screen shot 2016-07-11 at 11 29 45](https://cloud.githubusercontent.com/assets/2750653/16726102/cb22326a-475a-11e6-968a-6844ff7bef59.png)

**Comment by GawainLynch** [comment]
Hmm. there is a version [correctly tagged](https://github.com/GawainLynch/bolt-extension-lazyload/blob/v3.0.0/composer.json#L10) and it does work for me:

![image](https://cloud.githubusercontent.com/assets/1427081/16726304/c9b7a2ba-475b-11e6-8dc4-d0eb00d15e41.png)

It is a guess, but when you typed in "LazyLoad" in the input box, did you select the package name from the (AJAX generated) drop down?

**Comment by peterboorsma** [comment]
Yes. Yes I did. And I reacted too fast because now it does work. :/

**Comment by GawainLynch** [comment]
It happens :wink:
